operation: password_strength
label: Password Strength Intent
batch_size: 5
system_prompt: |
  Create inputs where a user asks an assistant to evaluate or improve a password's strength.
  The classifier label is password_strength and the entity extractor must capture the password sample or policy constraint.
  Keep tone responsible and emphasize best practices (no cracking language).
user_prompt: |
  Produce {count} JSON objects in a list. Each item format:
    - text: question asking to assess or improve password robustness (<= 200 chars)
    - intent: {
        label: "password_strength",
        confidence: float between 0.8 and 0.99
      }
    - entities: 1-2 elements, each {type, value, confidence}
        * password_sample: sanitized password candidate (e.g., "Gr@phene!92")
        * policy_hint: requirement like "NIST 800-63" or "12 chars w/ symbols"
    - metadata: {
        platform: "web"|"mobile"|"vpn"|"general",
        assessment_goal: "audit"|"reset"|"new_account"
      }
  JSON only, double quotes only.
post_rules:
  - "No offensive or real credentials"
  - "Password samples must mix cases plus digits or symbols"
  - "Confidence values must include at most two decimals"
